version: 2.1
jobs:

  build:
    docker:
      - image: docker:20.10.5-git
    steps:
      - checkout
      - run: docker build --tag sineverba/testphp56xc .
      - run: mkdir -p ~/docker
      - run: docker save -o ~/docker/testphp56xc.tar sineverba/testphp56xc
      - persist_to_workspace:
          root: ~/docker
          paths:
            - .

  test-docker:
    docker:
      - image: docker:20.10.5-git
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load -i /tmp/workspace/testphp56xc.tar
      - run: docker run --rm sineverba/testphp56xc php -v | grep 5.6.40
      - run: docker run --rm sineverba/testphp56xc php -v | grep OPcache
      - run: docker run --rm sineverba/testphp56xc php -m | grep xdebug
      - run: docker run --rm sineverba/testphp56xc php -r "echo phpversion('xdebug');" | grep "2.5.5"
      - run: docker run --rm sineverba/testphp56xc php -m | grep pdo_pgsql
      - run: docker run --rm sineverba/testphp56xc /usr/bin/composer -V | grep "1.10.20"
      - run: docker run --rm sineverba/testphp56xc php -i | grep "short_open_tag => Off => Off"
      - run: docker run --rm sineverba/testphp56xc php -i | grep "memory_limit => 512M => 512M"


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test-docker